theme: jekyll-theme-minimal
title: "DAKIR – подписка"
description: "Оплата подписки приложения DAKIR через YooKassa"
lang: ru
# Дополнительно можно указать ссылку на репозиторий
# repository: jmckckasdakaevadam971/desktop-subscription
